name: envpick
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.4.0
  - attrs=23.1.0
  - aws-c-auth=0.7.3
  - aws-c-cal=0.6.2
  - aws-c-common=0.9.0
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.2
  - aws-c-http=0.7.12
  - aws-c-io=0.13.32
  - aws-c-mqtt=0.9.5
  - aws-c-s3=0.3.14
  - aws-c-sdkutils=0.1.12
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.23.0
  - aws-sdk-cpp=1.10.57
  - blas=1.0
  - blosc=1.21.4
  - boost-cpp=1.78.0
  - bottleneck=1.3.5
  - branca=0.6.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - cairo=1.16.0
  - certifi=2023.7.22
  - cfitsio=4.2.0
  - charset-normalizer=3.2.0
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - contourpy=1.1.0
  - curl=8.2.1
  - cycler=0.11.0
  - expat=2.5.0
  - fiona=1.9.4
  - folium=0.14.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.42.1
  - freetype=2.12.1
  - freexl=1.0.6
  - gdal=3.7.1
  - geopandas=0.13.2
  - geopandas-base=0.13.2
  - geos=3.12.0
  - geotiff=1.7.1
  - gettext=0.21.1
  - giflib=5.2.1
  - hdf4=4.2.15
  - hdf5=1.14.1
  - icu=72.1
  - idna=3.4
  - importlib-metadata=6.8.0
  - jinja2=3.1.2
  - joblib=1.3.2
  - json-c=0.16
  - kealib=1.5.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.15
  - lerc=4.0.0
  - libaec=1.0.6
  - libarchive=3.6.2
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=8.2.1
  - libcxx=16.0.6
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.4
  - libgdal=3.7.1
  - libgfortran=5.0.0
  - libgfortran5=12.3.0
  - libglib=2.76.4
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.9.2
  - libnghttp2=1.52.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=15.4
  - librttopo=1.1.0
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libsqlite=3.43.0
  - libssh2=1.11.0
  - libtiff=4.5.1
  - libwebp-base=1.3.1
  - libxcb=1.15
  - libxml2=2.11.5
  - libzip=1.10.1
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.5.0
  - markupsafe=2.1.3
  - matplotlib-base=3.7.2
  - munch=4.0.0
  - munkres=1.1.4
  - ncurses=6.4
  - networkx=3.1
  - nspr=4.35
  - nss=3.92
  - numexpr=2.8.4
  - numpy=1.25.2
  - numpy-base=1.25.2
  - openjpeg=2.5.0
  - openssl=3.1.2
  - packaging=23.1
  - pandas=2.0.3
  - pcre2=10.40
  - pillow=10.0.0
  - pip=23.2.1
  - pixman=0.40.0
  - platformdirs=3.10.0
  - pooch=1.7.0
  - poppler=23.07.0
  - poppler-data=0.4.12
  - postgresql=15.4
  - proj=9.2.1
  - pthread-stubs=0.4
  - pyparsing=3.0.9
  - pyproj=3.6.0
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2022.7
  - rasterio=1.3.8
  - rasterstats=0.19.0
  - readline=8.2
  - requests=2.31.0
  - rtree=1.0.1
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - setuptools=68.0.0
  - shapely=2.0.1
  - simplejson=3.19.1
  - six=1.16.0
  - snappy=1.1.10
  - snuggs=1.4.7
  - sqlite=3.41.2
  - threadpoolctl=3.2.0
  - tiledb=2.13.2
  - tk=8.6.12
  - tqdm
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - tzcode=2023c
  - tzdata=2023c
  - urllib3=2.0.4
  - wheel=0.38.4
  - xerces-c=3.2.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2023.7.0
  - xz=5.4.2
  - zipp=3.16.2
  - zlib=1.2.13
  - zstd=1.5.5
